# Sidebar navigation

- label: 'Introduction'
  link: '/'
  items:
    - label: 'The native module'
      link: '/introduction/native-module'
    - label: 'The API for building native module'
      link: '/introduction/history'
    - label: 'Release native module'
      link: '/introduction/release'
    - label: 'Getting started'
      link: '/introduction/getting-started'
- label: Concepts
  items:
    - label: 'Env'
      link: '/concepts/env'
    - label: 'JS Values'
      link: '/concepts/js-values'
    - label: 'Reference'
      link: '/concepts/ref'
    - label: 'Task'
      link: '/concepts/task'
    - label: 'Thread safe function'
      link: '/concepts/thread-safe-function'
    - label: 'Wrap native value to Object'
      link: '/concepts/wrap'
    - label: 'Tokio'
      link: '/concepts/tokio'

- label: Recipes
  items:
    - label: 'Registering module'
      link: '/recipes/registering-module'
    - label: 'CallContext'
      link: '/recipes/call-context'
    - label: 'Define class'
      link: '/recipes/define-class'

- label: Ecosystem
  items:
    - label: swc
      link: /ecosystem/swc
    - label: '@node-rs/bcrypt'
      link: /ecosystem/@node-rs/bcrypt
    - label: '@node-rs/crc32'
      link: /ecosystem/@node-rs/crc32
    - label: '@node-rs/jieba'
      link: /ecosystem/@node-rs/jieba
    - label: '@node-rs/deno-lint'
      link: /ecosystem/@node-rs/deno-lint
    - label: '@napi-rs/pinyin'
      link: /ecosystem/@napi-rs/pinyin
    - label: '@napi-rs/skia'
      link: /ecosystem/@napi-rs/skia

- label: Changelog
  items:
    - label: '1.0.0'
      link: /changelog/1.0.0
    - label: '1.0.1'
      link: /changelog/1.0.1
    - label: 'napi@1.1.0'
      link: /changelog/napi-1.1.0
    - label: 'napi@1.1.1'
      link: /changelog/napi-1.1.1
    - label: '@napi/cli@1.0.1'
      link: /changelog/napi-cli-1.0.1

- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Compare with neon
      link: /neon
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/napi-rs/napi-rs
