name: Deploy to vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-cache

      - name: 'Install dependencies'
        run: |
          yarn global add pnpm
          pnpm install --frozen-lockfile --registry https://registry.npmjs.org

      - name: 'Deploy'
        run: pnpx vercel --confirm --prod -t $NOW_TOKEN
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}

      - name: 'Deploy CN'
        run: |
          echo "{\"projectId\":\"${CN_PROJECT_ID}\",\"orgId\":\"${CN_ORG_ID}\"}" > .vercel/project.json
          npx vercel --confirm --prod -t $NOW_TOKEN
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
          CN_ORG_ID: ${{ secrets.CN_ORG_ID }}
          CN_PROJECT_ID: ${{ secrets.CN_PROJECT_ID }}
